feat: 1.0.6 버전 업데이트에 따른 기능 추가 및 수정
YAPP-Github/Pokit-iOS pull request #166
Opened 2024-12-02 14:05 UTC by ShapeKim98

## #️⃣연관된 이슈

> #157 

## 📝작업 내용
- 링크 미리보기 스켈레톤 ui 적용
- `PokitIconLInput`, `PokitIconRInput`을 `PokitTextInput`으로 통일
- 텍스트 필드를 쓰는 모든 기능에 텍스트 지우기 버튼 추가
- 컨텐츠 추가에서 포킷 추가 버튼 변경사항 반영
- `PokitLinkPopup` 변경
- 컨텐츠 상세 플로우 변경사항 반영
- `PokitListButton` 추가
- `ContentDetail` 기능 변경사항 반영
- `PokitTextArea`에 메모 상태 추가
- `dismissKeyboard` `modifer` 추가
- `ContentCard`에 즐겨찾기 수정 기능 추가
- 재파싱한 썸네일 url 업데이트 API 적용
- `Lazy`한 뷰에서 `Store Scope`시 발생하는 스레드 안정성 문제 수정

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

### 스크린샷 (선택)

![Simulator Screen Recording - iPhone 16 Pro - 2024-12-02 at 22 22 15](https://github.com/user-attachments/assets/a5e580e8-6893-4908-8876-e7222e67f289) | ![Simulator Screen Recording - iPhone 16 Pro - 2024-12-02 at 22 24 27](https://github.com/user-attachments/assets/b6b59448-d855-491c-a29c-e5682392eff1)
--- | ---
 ![Simulator Screen Recording - iPhone 16 Pro - 2024-12-02 at 22 25 33](https://github.com/user-attachments/assets/37505928-394d-47b8-913b-7bc7765e64e8) | ![Simulator Screen Recording - iPhone 16 Pro - 2024-12-02 at 22 23 57](https://github.com/user-attachments/assets/8792f618-6ab9-4800-91dc-4a2e62b919a6)
--- | ---

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
### `PokitIconLInput`, `PokitIconRInput`을 `PokitTextInput`으로 통일하였습니다
- 최근 PM 요청 사항으로 모든 텍스트 필드에 텍스트 지우기 버튼이 있었으면 좋겠다는 요청이 있어 이를 반영중에 기존 텍스트 필드가 너무 유연하지 않다는 것을 깨달았습니다.
기존 `PokitIconL/RInput`이 `PokitTextInput`과 상당히 달랐고, 지우기 버튼 하나 넣는데에 코드를 좀 바꿨어야 했습니다. 그래서 `PokitTextInput`으로 통일했습니다.
- 그동안 디자인 시스템을 너무 막 만들었단 생각이 많이 드는거 같아요... 많이 반성하고 있습니다..ㅠ 추후에 버튼 컴포넌트도 통일할 예정입니다.
```Swift
PokitTextInput(
    text: $store.text,
    type: store.text.isEmpty ? .text : .iconR(
        icon: .icon(.x),
        action: { send(.닉네임지우기_버튼_눌렀을때) }
    ),
    shape: .rectangle,
    state: $store.textfieldState,
    info: "한글, 영어, 숫자로만 입력이 가능합니다.",
    maxLetter: 10,
    focusState: $isFocused,
    equals: true
)

PokitTextInput(
    text: $store.nicknameText,
    shape: .rectangle,
    state: $store.textfieldState,
    info: "한글, 영어, 숫자로만 입력이 가능합니다.",
    maxLetter: 10,
    focusState: $isFocused,
    equals: true
)
```
### `PokitLinkPopup` 변경
- `PokitLinkPopup`도 위와 같은 이유로 좀 더 유연하게 바꿨습니다.
```Swift
PokitLinkPopup(
    type: .constant(.link(
        title: "복사한 링크 저장하기",
        url: "https://www.youtube.com/watch?v=xSTwqKUyM8k"
    ))
)

PokitLinkPopup(
    type: .constant(.text(title: "최대 30개의 포킷을 생성할 수 있습니다.\n포킷을 삭제한 뒤에 추가해주세요."))
)

PokitLinkPopup(
    type: .constant(.success(title: "링크저장 완료"))
)

PokitLinkPopup(
    type: .constant(.error(title: "링크저장 실패"))
)

PokitLinkPopup(
    type: .constant(.warning(title: "저장공간 부족"))
)
```

### `PokitListButton` 컴포넌트를 새로 추가하였습니다.
- `PokitListButton`은 피그마 컴포넌트 페이지에 있는 `list_ver2` 컴포넌트 인데요, 이것 역시 기존 `PokitBottomSheet`가 너무 유연하지 않다는 생각이 들어 새로 추가하였습니다.
`PokitBottomSheet`는 디자이너들도 컴포넌트에 잘못 만들었다고 해주셔서 점차 `PokitListButton`으로 대체하겠습니다.
```Swift
#Preview {
    @Previewable
    @State var isOn: Bool = false
    
    PokitListButton(
        title: "공지사항",
        type: .default(icon: .icon(.arrowRight)),
        action: { }
    )
    
    PokitListButton(
        title: "공지사항",
        type: .bottomSheet(icon: .icon(.edit)),
        action: { }
    )
    
    PokitListButton(
        title: "공지사항",
        type: .subText(
            icon: .icon(.arrowRight),
            subeText: "포킷에 저장된 링크가 다른 사용자에게 추천됩니다."
        ),
        action: { }
    )
    
    PokitListButton(
        title: "공지사항",
        type: .toggle(subeText: "포킷에 저장된 링크가 다른 사용자에게 추천됩니다."),
        isOn: $isOn,
        action: { }
    )
}
```
### `dismissKeyboard` `modifer` 추가하였습니다.
- 키보드 외 영역을 터치하면 키보드가 내려가는 역할을 하며, `Modifier`이긴 하나, 디자인적 요소보단 기능적 요소에 가까운것 같아 `Util`에 구현하였습니다. 의견 있으시면 말씀해주세여
```Swift
extension View {
    public func dismissKeyboard(
        focused: FocusState<Bool>.Binding
    ) -> some View {
        self
            .overlay {
                if focused.wrappedValue {
                    Color.clear
                        .contentShape(Rectangle())
                        .onTapGesture {
                            focused.wrappedValue = false
                        }
                }
            }
    }
    
    public func dismissKeyboard<Value: Hashable>(
        focused: FocusState<Value?>.Binding
    ) -> some View {
        self
            .overlay {
                if focused.wrappedValue != nil {
                    Color.clear
                        .contentShape(Rectangle())
                        .onTapGesture {
                            focused.wrappedValue = nil
                        }
                }
            }
    }
}
```
### 재파싱한 썸네일 url 업데이트 API 적용하였습니다.
- 기존에 인스타그램에 썸네일 조회 이슈가 있어 조회가 안될때마다 썸네일을 새로 파싱하는 로직을 추가하였습니다. #155
하지만, 우리 서버에 새로 파싱한 썸네일 url을 보내지 않고 내부적으로만 사용하다 보니 서버의 썸네일 url과 새로 파싱한 썸네일 url이 달라 이미지 캐싱 적용이 되지않는다는 문제가 있었습니다.
그래서 서버에 썸네일 업데이트 API를 요청하여 적용하였습니다.

### `Lazy`한 뷰에서 `Store Scope`시 발생하는 스레드 안정성 문제 수정하였습니다.
- `ContentCardFeature`를 새로 추가하면서 `Lazy`한 뷰에 `Store`를 사용할 일이 발생하였는데, 아래와 같은 경고를 마주쳤습니다.
<img width="740" alt="스크린샷 2024-12-01 17 51 38" src="https://github.com/user-attachments/assets/874508bd-22c5-4775-a866-0f2d0e3d1b25">
알려주신 코드를 통해 위와 같은 문제를 수정하였습니다. 

[코드](https://github.com/pointfreeco/swift-composable-architecture/blob/fb822844b287ed25ce95f226dd509cbd6f5dbe37/Sources/ComposableArchitecture/Observation/IdentifiedArray%2BObservation.swift#L113)

close #157

2024-12-03 00:06 UTC, stealmh commented
고생많으셨습니다 천천히 살펴볼게요~!

2024-12-03 00:15 UTC, stealmh commented on Projects/DSKit/Sources/Components/PokitTextArea.swift
> +               state != .memo(isReadOnly: false) {
요건 무슨조건인가요? state가 memo가 아닐 때 맞나요??

2024-12-03 00:16 UTC, stealmh commented on Projects/DSKit/Sources/Components/PokitTextArea.swift
> +    private var textCount: some View {
네이밍이 Int Type같아요

2024-12-03 00:29 UTC, stealmh commented on Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
>              }
```swift
case .뷰가_나타났을때:
if let id = state.domain.contentId {
    return .send(.async(.컨텐츠_상세_조회_API(id: id)))
} 

if let content = state.domain.content {
    state.memo = content.memo
    return .none
} 

return .none
```
요렇게 바꿔도 좋을 것 같아요 가동성이 글쎄

2024-12-03 03:15 UTC, stealmh commented on Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
> +            )
제가 느낀 디자인시스템은 모든곳에서 사용하기 위해서 많이(광적으로..?) 추상화되어있다고 생각이 들어요
이런부분에서는 구체화해서 내부로 숨겨버리는게 더 깔끔하지 않나 하는 제 의견입니다..

디쟌시스템 관련해서 길게 생각해보시져 같이!

2024-12-03 03:16 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
> +                state.linkPopup = .text(title: "최대 30개의 포킷을 생성할 수 있습니다.\n포킷을 삭제한 뒤에 추가해주세요.")
요런 타이틀들 Constants로 묶어서 관리하는게 유지보수하기 편해보여요

2024-12-03 03:17 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
> +            state.linkImageURL = imageURL ?? "https://pokit-storage.s3.ap-northeast-2.amazonaws.com/logo/pokit.png"
요것두 url 따로 관리

2024-12-03 03:22 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
> +            )
catch문보다가 문득 든 생각이 요런것두 액션으로 받아서 한번에 처리하는거 어떠신가요??
```swift
enum InnerAction {
   case error(Error) // or ErrorResponse
}
```

2024-12-03 03:26 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                                action: { send(.링크팝업_버튼_눌렀을때, animation: .pokitSpring) }
PokitLinkPopup 내부에서도 type에 대해 optional unwrapping을 하는 것으로 보이는데 내부적 처리로는 동작을 제대로 하지 못해서 외부에서도 nil 여부를 한번더 체크하는건가요??

2024-12-03 03:27 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                    ? store.title.isEmpty ? "제목을 입력해주세요" : store.title
위에서 말했던 Constants를 사용해 하드코딩된 String값을 비교하면 실수가 덜 할 것 같아요

2024-12-03 03:29 UTC, stealmh commented on Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
> +            }
한줄

2024-12-03 03:30 UTC, stealmh commented on Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
> +        return .none
않이 주석도 지워주세요

2024-12-03 03:36 UTC, stealmh requested changes
지울 코드도 엄청많았고 디자인시스템 꾸려서 적용하는게 쉽지는 않았을텐데 고생 너무 많았습니다..!! 짱짱
이것저것 소소하게 고칠 것들이나 궁금한 것들 남겨뒀습니다 😃

View Extension과 같은 경우에는 내부적으로 정해야 할 것 같아요 이것도 하루 날 잡고 모듈 별로 위치해야 할 것들 정리가 필요해보입니다! 일단은 그 위치에 놔두는 것 괜찮습니다

2024-12-03 13:23 UTC, ShapeKim98 commented on Projects/DSKit/Sources/Components/PokitTextArea.swift
> +               state != .memo(isReadOnly: false) {
넵 맞습니다! 디자인 보면 메모 표시할 땐 텍스트 카운트가 없어서 넣었습니다

2024-12-03 13:24 UTC, ShapeKim98 commented on Projects/DSKit/Sources/Components/PokitTextArea.swift
> +    private var textCount: some View {
음.. 한번 고민해보겠습니다

2024-12-03 13:24 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
>              }
넵!

2024-12-03 13:24 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
> +            )
넵! 좋습니다...!!

2024-12-03 13:25 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
> +            )
오 좋아여

2024-12-03 13:34 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                                action: { send(.링크팝업_버튼_눌렀을때, animation: .pokitSpring) }
```Swift
.onReceive(timer) { _ in
    guard second < 2 && type != nil else {
        closedPopup()
        return
    }
    second += 1
}
```
혹시 내부적 처리라는게 이걸 뜻하는건가요? 저 `type != nil`은 기존 코드에서 무작정 바꾸다 보니 저도 모르게 썼던거 같아요.. 없애겠습니다

2024-12-03 14:21 UTC, stealmh commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                                action: { send(.링크팝업_버튼_눌렀을때, animation: .pokitSpring) }
> ```swift
> .onReceive(timer) { _ in
>     guard second < 2 && type != nil else {
>         closedPopup()
>         return
>     }
>     second += 1
> }
> ```
> 
> 혹시 내부적 처리라는게 이걸 뜻하는건가요? 저 `type != nil`은 기존 코드에서 무작정 바꾸다 보니 저도 모르게 썼던거 같아요.. 없애겠습니다

넵 onReceive도 그렇고 64번째줄, 72번째줄도 type이 쓰이더라구여! 그거 관련해서 물어봤습니다

2024-12-04 05:09 UTC, ShapeKim98 commented on Projects/DSKit/Sources/Components/PokitTextArea.swift
> +               state != .memo(isReadOnly: false) {
오 넵 알겠습니다!

2024-12-04 05:10 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
> +                state.linkPopup = .text(title: "최대 30개의 포킷을 생성할 수 있습니다.\n포킷을 삭제한 뒤에 추가해주세요.")
오.. 반영해보겠습니다!

2024-12-04 05:10 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                                action: { send(.링크팝업_버튼_눌렀을때, animation: .pokitSpring) }
불필요한건 지우도록 하겠습니당

2024-12-04 05:41 UTC, ShapeKim98 commented on Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
> +                                action: { send(.링크팝업_버튼_눌렀을때, animation: .pokitSpring) }
> > ```swift
> > .onReceive(timer) { _ in
> >     guard second < 2 && type != nil else {
> >         closedPopup()
> >         return
> >     }
> >     second += 1
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 혹시 내부적 처리라는게 이걸 뜻하는건가요? 저 `type != nil`은 기존 코드에서 무작정 바꾸다 보니 저도 모르게 썼던거 같아요.. 없애겠습니다
> 
> 넵 onReceive도 그렇고 64번째줄, 72번째줄도 type이 쓰이더라구여! 그거 관련해서 물어봤습니다

64번째 줄은 팝업이 `link` 타입일 경우 url을 표시하기 위함이고, 72번째 줄은 `success` 타입일 경우 체크마크를 표시하기 위함입니다!

2024-12-04 06:17 UTC, stealmh approved these changes

2024-12-04 06:29 UTC, merged